#!/bin/env -S node --enable-source-maps --no-warnings --loader @hop/hiphop/lib/hiphop-loader.mjs
// generated by testrandom (1.5.0 - 49aecf5)
import * as hh from "@hop/hiphop";

const events = [null];

const prg = hiphop module() {
  inout g3276 = 10 combine (x, y) => (x + y);
  {
    if (g3276.now) {
      pragma { this.g3276.preval; }
    } else {
      pragma { this.g3276.preval; }
    }
    emit g3276(67);
  }
}

export const mach = new hh.ReactiveMachine(prg, { name: "bug-uncycle-c40f49a", verbose: -1 });
mach.outbuf = "";

try {
   events.forEach((e, i) => {
      mach.outbuf += (mach.name() + '[' + i + ']: '
         + JSON.stringify(mach.reactDebug(e)) + '\n')
   });
} catch (e) {
   mach.outbuf = "error\n";
}

// NODE_OPTIONS="--enable-source-maps --no-warnings --loader @hop/hiphop/lib/hiphop-loader.mjs" node out/hiphop-loopUnroll-trapUnroll-nonative-uncycle-2026-10-9-16:0/hiphop.hh.mjs
