#!/bin/env -S node --enable-source-maps --no-warnings --loader @hop/hiphop/lib/hiphop-loader.mjs
// generated by testrandom (1.5.0 - 7237610)
import * as hh from "@hop/hiphop";

const events = [{},null, null];

const prg = hiphop module() {
   inout g80716;
   trap80717: {
      fork {
         yield;
         break trap80717;
      } par {
	 trap80742: {
            yield;
            yield;
            emit g80716(8);
	 }
      }
   }
}

export const mach = new hh.ReactiveMachine(prg);
mach.outbuf = "";

try {
   events.forEach((e, i) => {
      mach.outbuf += (mach.name() + '[' + i + ']: '
         + JSON.stringify(mach.reactDebug(e)) + '\n')
   });
} finally {
   if (process.env.HIPHOP_TEST) {
      console.log(mach.outbuf);
   }
}
