#!/bin/env -S node --enable-source-maps --no-warnings --loader @hop/hiphop/lib/hiphop-loader.mjs
// generated by testrandom (1.5.0 - 45f75b7)
import * as hh from "@hop/hiphop";

const events = [null,null];

const prg = hiphop module() {
   loop {
      if (false) {
	 yield;
      } else {
         signal g5839 = 0 combine (x, y) => (x + y);
         emit g5839(42);
         yield;
         pragma { g5839.now; }
      }
   }
}

const opts = process.env.HIPHOP_TEST_LOOP === "rnca"
   ? { name: "rnca", loopUnroll: false, reincarnation: true, native: false }
   : (process.env.HIPHOP_TEST_LOOP === "unroll"
      ? { name: "unroll", loopUnroll: true, reincarnation: false, native: false }
      : { name: "default" });
export const mach = new hh.ReactiveMachine(prg, opts);
mach.outbuf = "";

events.forEach((e, i) => {
   mach.outbuf += (mach.name() + '[' + i + ']: '
      + JSON.stringify(mach.reactDebug(e)) + '\n')
});


// NODE_OPTIONS="--enable-source-maps --no-warnings --loader @hop/hiphop/lib/hiphop-loader.mjs" node default.hh.mjs
