#!/bin/env -S node --enable-source-maps --no-warnings --loader @hop/hiphop/lib/hiphop-loader.mjs
// generated by testrandom

import * as hh from "@hop/hiphop";

const events = [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];

const prg = hiphop module() {
  {
    signal g6074 combine (x, y) => x, g6075 combine (x, y) => x, g6076 combine (x, y) => x;
    every (!this.g6075.now) {
      abort (this.g6074.now && this.g6075.now) {
        {
          fork {
            ;
          } par {
            loop {
              yield;
            }
          }
          emit g6075(32);
        }
      }
    }
  }
}

const opts = {};

export const mach = new hh.ReactiveMachine(prg, opts);
mach.outbuf = "";

events.forEach((e, i) => {
   mach.outbuf += ('[' + i + ']: '
      + JSON.stringify(mach.reactDebug(e)) + '\n')});

