#!/bin/env -S node --enable-source-maps --no-warnings --loader @hop/hiphop/lib/hiphop-loader.mjs
// generated by testrandom (1.5.0 - 49aecf5)
import * as hh from "@hop/hiphop";

const events = [{"g7049":13},{}];

const prg = hiphop module() {
  inout g7049 = 10 combine (x, y) => (x + y), g7050 = 10 combine (x, y) => (x + y);
  loop {
    fork {
      yield;
    } par {
      if (g7050.nowval) {
        if (g7050.now) {
          ;
        } else {
          pragma { true; }
        }
      } else {
        if (g7049.pre) {
          emit g7050(86);
        } else {
          ;
        }
      }
    }
  }
}

export const mach = new hh.ReactiveMachine(prg, { name: "bug-uncycle-dfeedd1", verbose: -1 });
mach.outbuf = "";

try {
   events.forEach((e, i) => {
      mach.outbuf += (mach.name() + '[' + i + ']: '
         + JSON.stringify(mach.reactDebug(e)) + '\n')
   });
} catch (e) {
   mach.outbuf = "error\n";
}

// NODE_OPTIONS="--enable-source-maps --no-warnings --loader @hop/hiphop/lib/hiphop-loader.mjs" node out/hiphop-loopUnroll-trapUnroll-nonative-uncycle-2026-10-8-16:33/hiphop.hh.mjs
