#!/bin/env -S node --enable-source-maps --no-warnings --loader @hop/hiphop/lib/hiphop-loader.mjs
// generated by testrandom (1.5.0 - 49aecf5)
import * as hh from "@hop/hiphop";

const events = [{"g197":4}];

const prg = hiphop module() {
  inout g197 = 10 combine (x, y) => (x + y), g198 = 10 combine (x, y) => (x + y);
  if (g197.now) {
    if (0) {
      yield;
      if (g198.now) {
        emit g197(53);
      } else {
        ;
      }
    } else {
      if (g197.pre) {
        ;
      } else {
        emit g198(71);
      }
    }
  } else {
    ;
  }
}

export const mach = new hh.ReactiveMachine(prg, { name: "bug-uncycle-21ca0e6" });
mach.outbuf = "";

try {
   events.forEach((e, i) => {
      mach.outbuf += (mach.name() + '[' + i + ']: '
         + JSON.stringify(mach.reactDebug(e)) + '\n')
   });
} finally {
   console.log(mach.outbuf);
}

// NODE_OPTIONS="--enable-source-maps --no-warnings --loader @hop/hiphop/lib/hiphop-loader.mjs" node out/hiphop-loopUnroll-trapUnroll-nonative-uncycle-2026-10-9-11:30/hiphop.hh.mjs
