// generated by testrandom

import * as hh from "@hop/hiphop";

const events = [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];

const prg = hiphop module() {
   signal g43194;
   do {
      signal g43196, g43197;
      abort (this.g43196.now) {
         fork {
            do {
               yield;                
            } every (this.g43197.now)
         } par {
            if (false) {
               ;
            } else {
               emit g43196(66);
            }
         }            
      }
      emit g43194(97);
   } every (this.g43194.now);
}

export const mach = new hh.ReactiveMachine(prg);
mach.outbuf = "";
try {
   events.forEach((e, i) => {
      mach.outbuf += (i + ': ' + JSON.stringify(mach.reactDebug(e)) + '\n')
   });
} catch (e) {
   mach.outbuf = "causality error " + mach.age() + '\n';
}
