#!/bin/env -S node --enable-source-maps --no-warnings --loader @hop/hiphop/lib/hiphop-loader.mjs
// generated by testrandom (1.5.0 - 7abf03d)
import * as hh from "@hop/hiphop";

let buf = "";

const events = [{},{},{}, null];

const prg = hiphop module() {
   loop {
      signal g1442;
      yield;
      fork {
         yield;
	 pragma { buf = "emit"; }
      } par {
	 pragma { "nothing" };
      }
   }
}

const opts = process.env.HIPHOP_TEST_LOOP === "rnca"
   ? { name: "rnca", loopUnroll: false, reincarnation: true, native: false }
   : (process.env.HIPHOP_TEST_LOOP === "unroll"
      ? { name: "unroll", loopUnroll: true, reincarnation: false, native: false }
      : { name: "default" });
export const mach = new hh.ReactiveMachine(prg, opts);
mach.outbuf = "";

events.forEach((e, i) => {
   buf = "";
   let s = JSON.stringify(mach.reactDebug(e));
   mach.outbuf += (mach.name() + '[' + i + ']: '
      + buf + s + '\n');
});

if (process.env.HIPHOP_TEST) {
   console.log(mach.outbuf);
}
