#!/bin/env -S node --enable-source-maps --no-warnings --loader @hop/hiphop/lib/hiphop-loader.mjs
// generated by testrandom (1.5.0 - 7abf03d)
import * as hh from "@hop/hiphop";

let buf = "";

const events = [{"g1092":90},null];

const prg = hiphop module() {
   inout g1092 = 0 combine (x, y) => (x + y);
   {
      signal g1095 = 0 combine (x, y) => (x + y);
      loop {
         if (g1092.pre) {
	    pragma { buf += `${g1092.preval} ${g1092.pre} age=${mach.age()} `; }
	 }
         yield;
      }
   }
}

const opts = process.env.HIPHOP_TEST_LOOP === "rnca"
   ? { name: "rnca", loopUnroll: false, reincarnation: true, native: false }
   : (process.env.HIPHOP_TEST_LOOP === "unroll"
      ? { name: "unroll", loopUnroll: true, reincarnation: false, native: false }
      : { name: "default" });
export const mach = new hh.ReactiveMachine(prg, opts);
mach.outbuf = "";

events.forEach((e, i) => {
   buf = "";
   let s = JSON.stringify(mach.reactDebug(e));
   mach.outbuf += (mach.name() + '[' + i + ']: '
      + buf + s + '\n');
});

if (process.env.HIPHOP_TEST_LOOP) {
   console.log(mach.outbuf);
}
