#!/bin/env -S node --enable-source-maps --no-warnings --loader @hop/hiphop/lib/hiphop-loader.mjs
// generated by testrandom (1.5.0 - 7abf03d)
import * as hh from "@hop/hiphop";

let buf = "";

const events = [null,null, null];

const prg = hiphop module() {
  loop {
     {
	pragma { buf += "A"; }
	L: { 
	   pragma { buf += "B"; }
	   yield;
	   pragma { buf += "C"; }
	   break L;
	}
	pragma { buf += "D"; }
     }
  }
}

const opts = process.env.HIPHOP_TEST === "reincarnation"
   ? { name: "rnca", loopUnroll: false, reincarnation: true, native: false }
   : (process.env.HIPHOP_TEST === "unroll"
      ? { name: "unroll", loopUnroll: true, reincarnation: false, native: false }
      : { name: "default" });
export const mach = new hh.ReactiveMachine(prg, opts);
mach.outbuf = "";

events.forEach((e, i) => {
   buf = "";
   let s = JSON.stringify(mach.reactDebug(e));
   mach.outbuf += (mach.name() + '[' + i + ']: '
      + buf + '\n');
});

if (process.env.HIPHOP_TEST) {
   console.log(mach.outbuf);
}
