#!/bin/env -S node --enable-source-maps --no-warnings --loader @hop/hiphop/lib/hiphop-loader.mjs
// generated by testrandom (1.5.0 - 7237610)
import * as hh from "@hop/hiphop";

const prg = hiphop module() {
  {
    signal g2760 = 11 combine (x, y) => (x + y);
    trap2761: {
      fork {
        loop {
          {
            emit g2760(40);
            yield;
          }
        }
      } par {
        break trap2761;
      }
    }
  }
}

export const mach = new hh.ReactiveMachine(prg);
mach.outbuf = "";

mach.outbuf += JSON.stringify(mach.reactDebug());
mach.outbuf += "\n";
mach.outbuf += JSON.stringify(mach.reactDebug());
mach.outbuf += "\n";

if (process.env.HIPHOP_TEST) {
   console.log(mach.name() + "...");
   console.log(mach.outbuf);
}

