/*=====================================================================*/
/*    serrano/prgm/project/hiphop/hiphop/testrandom/racket.mjs         */
/*    -------------------------------------------------------------    */
/*    Author      :  Manuel Serrano                                    */
/*    Creation    :  Fri Oct 24 16:29:15 2025                          */
/*    Last change :  Fri Oct 24 18:20:24 2025 (serrano)                */
/*    Copyright   :  2025 Manuel Serrano                               */
/*    -------------------------------------------------------------    */
/*    Testing some programs with racket/esterel                        */
/*=====================================================================*/

/*---------------------------------------------------------------------*/
/*    The module                                                       */
/*---------------------------------------------------------------------*/
export { ReactiveMachine };
import { writeFileSync } from "node:fs";
import { spawnSync } from "child_process";

/*---------------------------------------------------------------------*/
/*    json2racket ...                                                  */
/*---------------------------------------------------------------------*/
function json2racket(o) {

   function expr2racket(expr) {
      if (expr === "false") {
	 return "#f";
      } else if (expr === "true") {
	 return "#t";
      } else {
	 let m = expr.match(/![(](.*)[)]/);

	 if (m) {
	    return `(not ${expr2racket(m[1])})`;
	 }

	 if (m = expr.match(/this[.]([a-zA-Z0-9_]*)[.]now/)) {
	    return `(present? ${m[1]})`;
	 }

	 if (m = expr.match(/this[.]([a-zA-Z0-9_]*)[.]pre/)) {
	    return `(present? ${m[1]} #:pre 1)`;
	 }

	 throw TypeError(`Unsupported expression ${expr}`);
      }
   }
   
   function childrenOf(o) {
      if (o.children.length === 1) {
	 return json2racket(o.children[0]);
      } else {
	 return `(begin ${o.children.map(json2racket).join("\n")})`;
      }
   }

   function if2racket({func, children}) {
      return `(if ${expr2racket(func)} ${json2racket(children[0])} ${json2racket(children[1])})`
   }
   
   switch (o.node) {
      case "module":
	 return `(esterel ${childrenOf(o)})`;
      case "loop":
	 return `(loop ${childrenOf(o)})`;
      case "if":
	 return if2racket(o);
      case "local":
	 return `(with-signal (${o.signals.join(" ")}) ${childrenOf(o)})`;
      case "nothing":
	 return "(void)";
      case "pause":
	 return "(pause)";
      case "seq":
	 return childrenOf(o);
      case "trap":
	 return `(with-trap ${o.trapName} ${childrenOf(o)})`;
      case "exit":
	 return `(exit-trap ${o.trapName})`;
      case "par":
	 return `(par ${childrenOf(o)})`;
      case "atom":
	 return expr2racket(o.func);
      case "emit":
	 return `(emit ${o.signame})`;
      default:
	 console.error(JSON.stringify(o));
	 throw TypeError(`Unsupported node ${o.node}`);
   }
}

/*---------------------------------------------------------------------*/
/*    runRacket ...                                                    */
/*---------------------------------------------------------------------*/
function runRacket(file) {

   const child = spawnSync("racket", [file]);
   return [{ "status": "failure", signals: {} }];
}

/*---------------------------------------------------------------------*/
/*    ReactiveMachine ...                                              */
/*---------------------------------------------------------------------*/
function ReactiveMachine(prog, opts) {
   const rktfile = "/tmp/prog.hh.rkt";
   const eventsfile = "/tmp/prog.events.rkt";
   const events = [];
   const rktProg =
      ";; generated by testrandom\n"
      + "#lang racket\n"
      + ("(require esterel/full)\n\n")
      + (`(define machine ${json2racket(prog.tojson())})\n\n`)
      + (`(let ((events (call-with-input-file "/tmp/prog.events.rkt" read)))\n`)
      + (`   (map (lambda (e) (react! machine)) events))\n`);

   writeFileSync(rktfile, rktProg);

   return { file: rktfile,
	    name() { return opts.name || "racket" },
	    react(e) { events.push("()") },
	    end() { writeFileSync(eventsfile, `'(${events.join(" ")})`); return runRacket(rktfile) },
	    opts: {} };
}


