#!/bin/bash

space="     "
dir=$(pwd)
hop="/usr/local/bin/hop"
hop_opt="--no-server -g"
CC=/usr/bin/gcc
batchfile=/tmp/batch.js
output_hop=/tmp/TEST-HOPJS.out

run_test() {
    i=$((i + 1))

    echo -n "$i. $file ... "

    if [ -f $file.in ]; then
	cat <<EOF > $batchfile
"use hopscript"
"use strict"

const batch = require("hiphop");
let test = require("$dir/$file.js");

if (test.prg)
   try {
      batch.batch(test.prg);
   } catch(e){
      console.log(e.message);
      process.exit(1);
   }
EOF
	$hop $hop_opt $batchfile < $file.in > $output_hop
    else
	$hop $hop_opt $file.js > $output_hop
    fi
    diff_out=$(diff -Z $output_hop $file.out)

    if [ "$diff_out" != "" ]
    then
	echo -en "\e[31m\e[1mfailure\e[0m"
	failure=`expr $failure + 1`
    else
	echo -en "\e[32m\e[1mok\e[0m"
	success=`expr $success + 1`
    fi

    echo ".";
}

init_stats() {
    i=0
    success=0
    failure=0
}

print_stats() {
    echo -e "\e[1m$space*** $success success   $failure failure ***\e[0m"
}

if [ "$(dirname $0)" != "." ]
then
    echo "ERROR: The tests must be run inside test directory"
    exit 1
fi

if [ "$1" != "" ]; then
    file=${1%.*}
    if [ -f $file.out ]; then
	echo -e "\e[1m$space*** DEBUG TEST FOR $file. ***"
	echo -e "$space*** TMP FILES WILL NOT BE REMOVED ***\e[0m"
	run_test
	exit 0
    fi
fi

init_stats
clear
echo -e "\e[1m$space*** HIPHOP.JS TESTS ***\e[0m"
for file in *.out
do
    file=${file%.*}
    if [ -f $file.js ]; then
	run_test
    fi
done
print_stats

rm $batchfile
rm $output_hop
