FROM hop

WORKDIR /tmp

RUN rm -rf /tmp/*

USER hop
ENV HOME /home/hop

STOPSIGNAL SIGINT

RUN git clone https://github.com/manuel-serrano/hiphop.git \
    && (cd hiphop; git checkout master; cd doc; make ) \
    && (cp -r hiphop/doc /usr/local/share/doc/hiphop) \
    && mv hiphop /usr/local/lib/hop/@HOPVERSION@/node_modules
    
ENTRYPOINT ["/bin/bash"]
ENTRYPOINT ["/usr/local/bin/hop"]

